apiVersion: v1
kind: Service
metadata:
  name: kyma-ml-example
  labels:
    app: kyma-ml-example
spec:
  ports:
  - name: http
    port: 8888
  selector:
    app: kyma-ml-example

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyma-ml-example
spec:
  selector:
    matchLabels:
      app: kyma-ml-example
  replicas: 2
  template:
    metadata:
      labels:
        app: kyma-ml-example
    spec:
      containers:
        - image: your-dockerID/kyma-ml-example
          name: helloworld
          ports:
          - containerPort: 8888